***
<h1 style='color: Darkblue; font-size: 36px; font-weight: bold;'>DESCRIÇÃO DO PROJETO</h1>

***
<h1 style='color: Darkblue; font-size: 25px; font-weight: bold;'>Condições Iniciais e Resultados Futuros:</h1>
    
<h1 style='color: Darkblue; font-size: 25px; font-weight: bold;'>Uma Avaliação de Impacto do Programa Mãe Coruja Pernambucana (PMCP) Sobre o Desempenho Escolar das Crianças</h1>

***
<h1 style='color: Darkblue; font-size: 18px; font-weight: bold;'>Neste projeto, tentaremos capturar o efeito causal do Programa Mãe Coruja Pernambucana sobre o desempenho escolar das crianças afetadas, com base nas proficiências médias das escolas divulgadas pelo Sistema de Avaliação Educacional de Pernambuco (SAEPE)</h1>

***

# <font color='darkblue'>PROGRAMA MÃE CORUJA PERNAMBUCANA (PMCP) </font>
<hr style='border: 2px solid darkblue;'>

### Implementado em 2008, no estado de Pernambuco, o Programa Mãe Coruja Pernambucana tinha como objetivo reduzir os altos índices de mortalidade infantil e materna no estado de Pernambuco.
    
### O PMCP atua por meio de uma extensa rede de ações calcadas em assistências no pré-natal, acompanhamento das crianças e auxílio durante a primeira infância, das quais o amparo ao período gestacional da mulher se destaca como o seu maior enfoque.

### Implementação:

***
#### A escolha da região e dos municípios por onde o programa começaria a ser implantado obedeceu a alguns critérios, sendo levada, ainda, em consideração as onze Gerências Regionais de Saúde (Geres) responsáveis pelos 185 municípios do estado. 

#### Os principais critérios utilizados foram a taxa de mortalidade infantil, os Índice de Desenvolvimento Humano (IDH) e Índice de Desenvolvimento Infantil (IDI). Seriam considerados aqueles municípios que possuíssem uma taxa de mortalidade infantil maior ou igual a 25 óbitos a cada mil nascidos vivos e que apresentassem baixos IDH e IDI. Além disso, determinou-se que o programa seria implantado em todos os municípios das Geres para os casos em que ao menos 50\% dos municípios nela situados  detivessem uma taxa de mortalidade infantil superior a 25 óbitos por mil nascidos vivos.


#### Com base nesses parâmetros, a implementação iniciou-se pela microregião de Araripina (Sertão do Araripe), seguida pelo Sertão do Moxotó (VI Geres). Desse modo, 24 municípios foram contemplados pelo PMCP em sua primeira fase de implementação. Ao longo dos anos o programa se ampliou de forma a atuar, atualmente, em 105 dos 185 municípios do estado.

#### A seguinte tabela fornece os anos de participação de cada município de Pernambuco no programa:

***

In [545]:
pd.read_excel('Dados/tabela_de_participacao.xls', index_col=0)

,Códigos dos Municípios,Participação dos Municípios no Programa Mãe Coruja Pernambucana ao longo do período de 2007 a 2014,2007,2008,2009,2010,2011,2012,2013,2014
0,2600054,Abreu e Lima,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
1,2600104,Afogados da Ingazeira,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
2,2600203,Afrânio,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM
3,2600302,Agrestina,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM
4,2600401,Água Preta,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
...,...,...,...,...,...,...,...,...,...,...
180,2616183,Vertente do Lério,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
181,2616209,Vertentes,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM
182,2616308,Vicência,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
183,2616407,Vitória de Santo Antão,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
184,2616506,Xexéu,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM

### Ações Específicas do Programa:
***
<ul style='font-size: 14px; line-height: 2; text-align: justify;'>
    <li><b>círculos de educação e cultura</b></li>
    <li><b>cursos de qualificação profissional para as mães</b></li>
    <li><b>oficinas de segurança alimentar e nutricional</b></li>
    <li><b>inclusão em programas sociais nos Centros Regionais de Assistência Social</b></li>
    <li><b>fornecimento de kits do bebê para as gestantes</b></li>
    <li><b>assistência ao pré-natal (com a realização de sete ou mais consultas)</b></li>
    <li><b>assistência ao parto e ao puerpério</b></li>
    <li><b>reorganização da rede de atenção ao parto</b></li>
    <li><b>incentivo ao aleitamento materno</b></li>
    <li><b>acompanhamento e incentivo da vacinação da criança</b></li>
    <li><b>acesso ao registro de nascimento</b></li>
    <li><b>acompanhamento do crescimento e do desenvolvimento da criança</b></li>
</ul> 

***

### Fontes: 

https://maecoruja.pe.gov.br/o-programa/

http://portal.saude.pe.gov.br/programa/secretaria-executiva-de-atencao-saude/programa-mae-coruja-pernambucana

Livro Mãe Coruja Pernambucana (os 4 volumes), contidos em: https://maecoruja.pe.gov.br/leituras-importantes/

***



### Essas ações desempenhadas pelo PMCP refletem impactos exógenos em uma série de variáveis que podem afetar os resultados futuros das crianças, como a qualidade do pré-natal e da primeira infância, além da qualidade nutricional e o grau de instrução dos pais, sendo expressos, por exemplo, através dos resultados escolares.

***

### Referências:

ALMOND, D.; MAZUMDER, B.; EWIJK, R. V. In utero ramadan exposure and children’sacademic performance. The Economic Journal, Oxford University Press Oxford, UK, v. 125,n. 589, p. 1501–1533, 2014.

BROWNELL, M. D. et al. A population-based analysis of factors that predict early language andcognitive development.Early Childhood Research Quarterly, Elsevier, v. 35, p. 6–18, 2016.

CARNEIRO, P. M.; HECKMAN, J. J. Human capital policy. IZA discussion paper, 2003.

CHORNIY, A. V.; CURRIE, J.; SONCHAK, L. Does Prenatal WIC Participation Improve Child Outcomes?[S.l.], 2018.

HECKMAN, J. J. et al. The rate of return to the highscope perry preschool program.Journal ofpublic Economics, Elsevier, v. 94, n. 1-2, p. 114–128, 2010.

HENRICHS, J. et al. Parental family stress during pregnancy and cognitive functioning in earlychildhood: The generation r study.Early Childhood Research Quarterly, Elsevier, v. 26, n. 3, p.332–343, 2011.

JUNIOR, M. V. W.; RIBEIRO, F. G.; PAESE, L. H. Z. Early childhood home-based programmesand school violence: evidence from brazil.Development in Practice, Taylor & Francis, p. 1–11,2021.

NISHIMURA, F. N.; MESQUITA, A. Efeitos do programa “primeira infância melhor” sobre os casos de desnutrição infantil,.In: ANPEC - 46ºEncontro Nacional de Economia, Rio deJaneiro-RJ, 2018

***

# <font color='darkblue'>SISTEMA DE AVALIAÇÃO EDUCACIONAL DE PERNAMBUCO (SAEPE) </font>
<hr style='border: 2px solid darkblue;'>

### O Sistema de Avaliação Educacional de Pernambuco (SAEPE) foi criado, em 2000, com o objetivo de aferir o desempenho dos alunos da rede pública e fomentar mudanças na educação oferecida pelo estado.

### Desde 2008, o programa passou por reestruturações, com avaliações em Língua Portuguesa e Matemática ocorrendo anualmente. Os dados, referentes ao desempenho dos estudantes dos Ensinos Fundamental e Médio, são disponibilizados em uma Plataforma criada em parceria com o CAEd/UFJF.

### O seguinte código retorna a base de dados do SAEPE para as avaliações de matemática, com dados desde 2008, que utilizaremos no projeto

In [548]:
pd.read_csv('Dados/mat.csv', index_col=0).head()

C:\Users\Admin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Rede,Código da Etapa,Etapa,Código da GRE,GRE,Código do Município,Município,Código da Escola,Escola,Edição,Proficiência Média,Desvio Padrão,Padrão de Desempenho,Elementar I,Elementar II,Básico,Desejável,Estudantes Previstos,Estudantes Efetivos,Percentual de Participação
Código da Rede,,,,,,,,,,,,,,,,,,,,
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050048,ESCOLA BENTO AMERICO,2008,"172,9","33,9",Elementar II,"27,7","32,3","35,4","4,6",-,65,-
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050102,ESCOLA JOAO MONTEIRO DE MELO,2008,"175,7","30,6",Elementar II,"18,7","48,0","25,3","8,0",-,75,-
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050137,ESCOLA MINISTRO MARCOS DE BARROS FREIRE,2008,"163,1","34,9",Elementar II,"35,9","34,4","25,0","4,7",-,64,-
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050188,ESCOLA PADRE GIOVANNI TONIUTTI,2008,"174,6","38,3",Elementar II,"28,3","32,1","30,2","9,4",-,53,-
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050200,ESCOLA PROFESSORA MARIA GALVAO,2008,"182,6","49,6",Elementar II,"31,4","22,9","28,6","17,1",-,35,-

### Para medir o efeito causal do PMCP, utilizaremos a coluna de "Proficiências Médias", como o resultado escolar.

### As colunas referentes aos municípios e anos (edição) serão a base para definirmos os grupos de tratamento e controle, com base no ano de entrada dos municípios no programa

### As colunas referentes às etapas (série escolar) e aos anos (edição) serão a base para definirmos os períodos pré e pós tratamento. Por exemplo, se formos analisar os 5º anos (que comporta crianças de 10 a 11 anos), temos que o período pré-tratamento se dá entre 2008 à 2017, sendo o ano de 2018 o primeiro período que o efeito causal pode ser capturado, pois as crianças expostas ao PMCP (nascidas a partir de 2008) estariam no 5º ano em 2018.

***

### Fonte: 

https://institucional.caeddigital.net/projetos/saepe-pe.html

***

<h1 style='color: green; font-size: 36px; font-weight: bold;'>Tratamento Inicial dos Dados</h1>

**Neste Notebook foi realizada a fase de tratamento inicial da base de dados.**

**Aqui foram corrigidos os problemas mais visíveis do nosso dataset.**

**O dataset também foi separada entre grupos de tratamento e controle, o que inclui descartar dados que não serviriam para identificar o efeito causal do programa (como inconsistências de dados nos períodos pré e pós tratamento).**

**Ao fim deste Notebook foram criadas algumas bases distintas de dados, com diferentes níveis de agregação e separadas ou não por grupos de tratamento e controle.**

**O tratamento dos dados com base em alguns problemas que podem vir a ser identificados a partir de uma análise mais profunda dos dados, como a investigação de outliers, por exemplo, serão abordadas posteriormente no Notebook "Análise Exploratória e Descritiva dos Dados".**

# <font color='red' style='font-size: 30px;'>Importando Pacotes</font>
<hr style='border: 2px solid red;'>

In [270]:
import pandas as pd
import numpy as np

# <font color='red' style='font-size: 30px;'>Conhecendo o Dataset</font>
<hr style='border: 2px solid red;'>

In [271]:
dados = pd.read_csv('Dados/mat.csv')
dados.head()

C:\Users\Admin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Código da Rede,Rede,Código da Etapa,Etapa,Código da GRE,GRE,Código do Município,Município,Código da Escola,Escola,...,Proficiência Média,Desvio Padrão,Padrão de Desempenho,Elementar I,Elementar II,Básico,Desejável,Estudantes Previstos,Estudantes Efetivos,Percentual de Participação
0,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050048,ESCOLA BENTO AMERICO,...,"172,9","33,9",Elementar II,"27,7","32,3","35,4","4,6",-,65,-
1,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050102,ESCOLA JOAO MONTEIRO DE MELO,...,"175,7","30,6",Elementar II,"18,7","48,0","25,3","8,0",-,75,-
2,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050137,ESCOLA MINISTRO MARCOS DE BARROS FREIRE,...,"163,1","34,9",Elementar II,"35,9","34,4","25,0","4,7",-,64,-
3,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050188,ESCOLA PADRE GIOVANNI TONIUTTI,...,"174,6","38,3",Elementar II,"28,3","32,1","30,2","9,4",-,53,-
4,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050200,ESCOLA PROFESSORA MARIA GALVAO,...,"182,6","49,6",Elementar II,"31,4","22,9","28,6","17,1",-,35,-

# <font color='red' style='font-size: 30px;'>Substituindo ',' por '.'  e excluindo linhas nulas nas Proficiências Médias</font>
<hr style='border: 2px solid red;'>

### De início, é perceptível que as variáveis quantitativas do dataset têm suas casas decimais separadas por vírgulas ao invés de pontos. 

### É necessário substituir essa vírgulas por pontos para conseguirmos transformar a coluna em numeric para podermos efetuar futuros cálculos. 

### Inicialmente, há interesse apenas na coluna relativa às proficiências médias, portanto, apenas ela passará por esse procedimento.

In [272]:
proficiencia = []

for item in dados['Proficiência Média']:
    proficiencia.append(item.replace(',','.'))

dados['Proficiência Média'] = proficiencia
dados['Proficiência Média'] = pd.to_numeric(dados['Proficiência Média'])

ValueError: Unable to parse string "-" at position 7707

### **O erro acima nos reporta que algumas linhas contém o caractere '-' para reportar valores inexistente.**

**O seguinte código substitui o '-' por NA, nos mermitindo facilmente remover observações nulas dos nossos dados.**

In [273]:
proficiencia = []

for item in dados['Proficiência Média']:
    proficiencia.append(item.replace(',','.').replace('-', ''))

dados['Proficiência Média'] = proficiencia
dados['Proficiência Média'] = pd.to_numeric(dados['Proficiência Média'], errors='coerce')
dados['Proficiência Média'] = dados['Proficiência Média'].astype(float)

In [274]:
dados.dropna(subset = ['Proficiência Média'], inplace = True)

**Também transformamos a coluna para numeric e em seguida para o tipo float. Como estamos apenas interessados na proficiência média, não repetiremos o processo para as demais colunas.**

# <font color='red' style='font-size: 30px;'>Separando por Etapas de Ensino</font>
<hr style='border: 2px solid red;'>

## Iremos separar nosso Dataset por etapas de ensino e verificar se elas possuem dados para seus períodos pré e pós tratamento.

### Lembrando que os períodos pré e pós tratamento dependem das idades das crianças relativas a cada série.

In [275]:
dados['Etapa'].unique()

array(['4ª SÉRIE/5º ANO EF', '8ª SÉRIE/9º ANO EF', '3º ANO EM',
       '2ª SÉRIE/3º ANO EF', '2ª SÉRIE / 3º ANO EF',
       '4ª SÉRIE / 5º ANO EF', '8ª SÉRIE / 9º ANO EF', '3ª SÉRIE EM',
       '2º ANO EF', '5º ANO EF', '9º ANO EF',
       'ENSINO FUNDAMENTAL DE 9 ANOS - 2º ANO',
       'ENSINO FUNDAMENTAL DE 9 ANOS - 5º ANO', 'ENSINO MÉDIO - 3ª SÉRIE',
       'ENSINO FUNDAMENTAL DE 9 ANOS - 9º ANO'], dtype=object)

**Existe mais de uma nomenclatura para algumas etapas de ensino**

**LEMBRETE: são considerados apenas os anos inicias do ensino fundamental, por serem os únicos expostos ao tratamento até 2018.**

## 2º Ano do Fundamental
<hr style='border: 2px solid black;'>

**7-8 anos de idade**

**Captura do efeito do tratamento: 2016-2018**

In [276]:
nomenclatura_etapa_segundo_ano = ['2º ANO EF', 'ENSINO FUNDAMENTAL DE 9 ANOS - 2º ANO']
nomenclatura_etapa_segundo_ano

['2º ANO EF', 'ENSINO FUNDAMENTAL DE 9 ANOS - 2º ANO']

In [277]:
dados_segundo_ano = dados[dados['Etapa'].isin(nomenclatura_etapa_segundo_ano)]
dados_segundo_ano['Edição'].unique()

array([2016, 2017, 2018], dtype=int64)

**Não conseguimos obter o período pré-tratamento (antes de 2016)**

**Portanto, a etapa não será considerada**

## 3º Ano do Fundamental
<hr style='border: 2px solid black;'>

**8-9 anos de idade**

**Captura do efeito do tratamento: 2016-2018**

In [278]:
nomenclatura_etapa_terceiro_ano = ['2ª SÉRIE/3º ANO EF', '2ª SÉRIE / 3º ANO EF', ]
nomenclatura_etapa_terceiro_ano

['2ª SÉRIE/3º ANO EF', '2ª SÉRIE / 3º ANO EF']

In [279]:
dados_terceiro_ano = dados[dados['Etapa'].isin(nomenclatura_etapa_terceiro_ano)]
dados_terceiro_ano['Edição'].unique()

array([2011, 2012, 2013, 2014, 2015], dtype=int64)

**Não conseguimos obter o período pós-tratamento**

**Portanto, a etapa não será considerada**

## 5º Ano do Ensino Fundamental 
<hr style='border: 2px solid black;'>

**10-11 anos de idade**

**Captura do efeito do tratamento: 2018**

In [280]:
nomenclatura_etapa_quinto_ano = ['4ª SÉRIE/5º ANO EF',
                                '4ª SÉRIE / 5º ANO EF',
                                '5º ANO EF', 
                                'ENSINO FUNDAMENTAL DE 9 ANOS - 5º ANO']
nomenclatura_etapa_quinto_ano

['4ª SÉRIE/5º ANO EF',
 '4ª SÉRIE / 5º ANO EF',
 '5º ANO EF',
 'ENSINO FUNDAMENTAL DE 9 ANOS - 5º ANO']

In [281]:
dados_quinto_ano = dados[dados['Etapa'].isin(nomenclatura_etapa_quinto_ano)]
dados_quinto_ano['Edição'].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018],
      dtype=int64)

**Conseguimos obter os períodos pré e pós tratamento.**

## <font color='red'> O 5º ano do ensino fundamental será a única etapa de ensino avaliada </font>

# <font color='red' style='font-size: 30px;'>Redefinindo a Varíavel 'dados' Para a Única Etapa a Ser Avaliada</font>
<hr style='border: 2px solid red;'>

In [282]:
dados = dados_quinto_ano
dados.head()

,Código da Rede,Rede,Código da Etapa,Etapa,Código da GRE,GRE,Código do Município,Município,Código da Escola,Escola,...,Proficiência Média,Desvio Padrão,Padrão de Desempenho,Elementar I,Elementar II,Básico,Desejável,Estudantes Previstos,Estudantes Efetivos,Percentual de Participação
0,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050048,ESCOLA BENTO AMERICO,...,172.9,"33,9",Elementar II,"27,7","32,3","35,4","4,6",-,65,-
1,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050102,ESCOLA JOAO MONTEIRO DE MELO,...,175.7,"30,6",Elementar II,"18,7","48,0","25,3","8,0",-,75,-
2,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050137,ESCOLA MINISTRO MARCOS DE BARROS FREIRE,...,163.1,"34,9",Elementar II,"35,9","34,4","25,0","4,7",-,64,-
3,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050188,ESCOLA PADRE GIOVANNI TONIUTTI,...,174.6,"38,3",Elementar II,"28,3","32,1","30,2","9,4",-,53,-
4,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050200,ESCOLA PROFESSORA MARIA GALVAO,...,182.6,"49,6",Elementar II,"31,4","22,9","28,6","17,1",-,35,-

# <font color='red' style='font-size: 30px;'>Separando os Grupos de Controle e Tratamento</font>
<hr style='border: 2px solid red;'>

## Obtendo os Códigos dos Grupos de Tratamento e Controle:

<hr style='border: 2px solid black;'>

In [283]:
participacao_no_PMCP = pd.read_excel('Dados/tabela_de_participacao.xls')

In [284]:
participacao_no_PMCP

,Unnamed: 0,Códigos dos Municípios,Participação dos Municípios no Programa Mãe Coruja Pernambucana ao longo do período de 2007 a 2014,2007,2008,2009,2010,2011,2012,2013,2014
0,0,2600054,Abreu e Lima,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
1,1,2600104,Afogados da Ingazeira,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
2,2,2600203,Afrânio,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM
3,3,2600302,Agrestina,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM
4,4,2600401,Água Preta,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
...,...,...,...,...,...,...,...,...,...,...,...
180,180,2616183,Vertente do Lério,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
181,181,2616209,Vertentes,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM
182,182,2616308,Vicência,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
183,183,2616407,Vitória de Santo Antão,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
184,184,2616506,Xexéu,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM

**Nosso grupo de tratamento são as escolas dos municípios que entraram no PMCP em 2008**

**Nosso grupo de controle são as escolas dos demais municípios**

**Para separá-las na nossa base de dados, devemos obter os códigos dos municípios entrantes e não entrantes no PMCP em 2008**

In [285]:
codigos_municipios_tratados = participacao_no_PMCP.query("`2008` == 'SIM'")['Códigos dos Municípios'].reset_index(drop=True)
codigos_municipios_tratados

0     2601102
1     2601201
2     2602001
3     2602803
4     2605103
5     2605301
6     2606309
7     2606606
8     2607000
9     2607307
10    2608057
11    2609154
12    2614303
13    2609907
14    2610400
15    2610806
16    2611002
17    2612455
18    2612554
19    2614105
20    2614808
21    2615607
22    2615805
23    2616001
Name: Códigos dos Municípios, dtype: int64

In [286]:
codigos_municipios_controle = participacao_no_PMCP.query("`2008` != 'SIM'")['Códigos dos Municípios'].reset_index(drop=True)
codigos_municipios_controle

0      2600054
1      2600104
2      2600203
3      2600302
4      2600401
        ...
156    2616183
157    2616209
158    2616308
159    2616407
160    2616506
Name: Códigos dos Municípios, Length: 161, dtype: int64

## Grupo de Tratamento:
<hr style='border: 2px solid black;'>

In [287]:
dados_grupo_de_tratamento = dados[dados['Código do Município'].isin(codigos_municipios_tratados)]
dados_grupo_de_tratamento.reset_index(drop=True, inplace=True)
dados_grupo_de_tratamento.head()

,Código da Rede,Rede,Código da Etapa,Etapa,Código da GRE,GRE,Código do Município,Município,Código da Escola,Escola,...,Proficiência Média,Desvio Padrão,Padrão de Desempenho,Elementar I,Elementar II,Básico,Desejável,Estudantes Previstos,Estudantes Efetivos,Percentual de Participação
0,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,111,SERTAO CENTRAL(SALGUEIRO),2610400,PARNAMIRIM,26010607,ESCOLA EUCLIDES DA CUNHA,...,162.0,"35,4",Elementar II,"41,2","33,3","23,5","2,0",-,51,-
1,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,111,SERTAO CENTRAL(SALGUEIRO),2614303,MOREILANDIA,26008467,ESCOLA CORONEL CHICO ROMAO,...,176.0,"44,5",Elementar II,"30,5","30,5","20,3","18,6",-,59,-
2,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,113,SERTAO DO ARARIPE(ARARIPINA),2602001,BODOCO,26001900,ESCOLA JOAO CARLOS LOCIO DE ALMEIDA,...,146.1,"39,0",Elementar I,"43,5","43,5","13,0","0,0",-,23,-
3,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,114,SERTAO DO MOXOTO IPANEMA(ARCOVERDE),2601201,ARCOVERDE,26024721,ESCOLA ANTONIO JAPIASSU,...,204.9,"43,4",Básico,"11,1","22,2","38,9","27,8",-,18,-
4,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,114,SERTAO DO MOXOTO IPANEMA(ARCOVERDE),2601201,ARCOVERDE,26024730,ESCOLA CARLOS RIOS,...,177.3,"39,4",Elementar II,"21,1","42,1","21,1","15,8",-,38,-

## Grupo de Controle
<hr style='border: 2px solid black;'>

In [288]:
dados_grupo_de_controle = dados[dados['Código do Município'].isin(codigos_municipios_controle)]
dados_grupo_de_controle.reset_index(drop=True, inplace=True)
dados_grupo_de_controle.head()

,Código da Rede,Rede,Código da Etapa,Etapa,Código da GRE,GRE,Código do Município,Município,Código da Escola,Escola,...,Proficiência Média,Desvio Padrão,Padrão de Desempenho,Elementar I,Elementar II,Básico,Desejável,Estudantes Previstos,Estudantes Efetivos,Percentual de Participação
0,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050048,ESCOLA BENTO AMERICO,...,172.9,"33,9",Elementar II,"27,7","32,3","35,4","4,6",-,65,-
1,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050102,ESCOLA JOAO MONTEIRO DE MELO,...,175.7,"30,6",Elementar II,"18,7","48,0","25,3","8,0",-,75,-
2,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050137,ESCOLA MINISTRO MARCOS DE BARROS FREIRE,...,163.1,"34,9",Elementar II,"35,9","34,4","25,0","4,7",-,64,-
3,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050188,ESCOLA PADRE GIOVANNI TONIUTTI,...,174.6,"38,3",Elementar II,"28,3","32,1","30,2","9,4",-,53,-
4,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050200,ESCOLA PROFESSORA MARIA GALVAO,...,182.6,"49,6",Elementar II,"31,4","22,9","28,6","17,1",-,35,-

# <font color='red' style='font-size: 30px;'>Agregando Por Municípios</font>
<hr style='border: 2px solid red;'>

**Iremos agregar os dados a nível municipal, tirando a média aritmética das proficiências médias das escolas**

In [289]:
dados_municipios = dados.groupby(['Código do Município', 'Edição'], as_index=False)['Proficiência Média'].mean()
dados_municipios.sort_values(['Código do Município','Edição'], inplace=True)
dados_municipios.rename(columns={'Código do Município': 'codigo_do_municipio', 
                                 'Edição': 'ano', 
                                 'Proficiência Média': 'proficiencia_media_matematica'},inplace=True)
dados_municipios

      codigo_do_municipio   ano  proficiencia_media_matematica
0                 2600054  2008                     166.225806
1                 2600054  2009                     167.251515
2                 2600054  2010                     169.137500
3                 2600054  2011                     177.648387
4                 2600054  2012                     176.574074
...                   ...   ...                            ...
2029              2616506  2014                     210.781818
2030              2616506  2015                     211.341667
2031              2616506  2016                     207.090909
2032              2616506  2017                     219.292308
2033              2616506  2018                     226.614286

[2034 rows x 3 columns]

**Checando se todos os municípios possuem dados em todos os anos**

In [290]:
dados_municipios.codigo_do_municipio.value_counts()

2600054    11
2611309    11
2610400    11
2610509    11
2610608    11
           ..
2605806    11
2606002    11
2606101    11
2616506    11
2605905    10
Name: codigo_do_municipio, Length: 185, dtype: int64

**O município com o código 2605905 não possui dados da proficiência média para todos os anos**    
**Portanto, será excluído da nossa base de dados**

In [291]:
dados_municipios = dados_municipios.query('codigo_do_municipio != 2605905')
dados_municipios

      codigo_do_municipio   ano  proficiencia_media_matematica
0                 2600054  2008                     166.225806
1                 2600054  2009                     167.251515
2                 2600054  2010                     169.137500
3                 2600054  2011                     177.648387
4                 2600054  2012                     176.574074
...                   ...   ...                            ...
2029              2616506  2014                     210.781818
2030              2616506  2015                     211.341667
2031              2616506  2016                     207.090909
2032              2616506  2017                     219.292308
2033              2616506  2018                     226.614286

[2024 rows x 3 columns]

## Grupo de Tratamento:
<hr style='border: 2px solid black;'>

In [293]:
selecao_municipios_tratamento = dados_municipios['codigo_do_municipio'].isin(codigos_municipios_tratados)
selecao_municipios_tratamento

0       False
1       False
2       False
3       False
4       False
        ...
2029    False
2030    False
2031    False
2032    False
2033    False
Name: codigo_do_municipio, Length: 2024, dtype: bool

In [294]:
dados_municipios_tratamento = dados_municipios[selecao_municipios_tratamento]
dados_municipios_tratamento.reset_index(drop=True, inplace=True)
dados_municipios_tratamento

     codigo_do_municipio   ano  proficiencia_media_matematica
0                2601102  2008                     164.428571
1                2601102  2009                     175.593258
2                2601102  2010                     172.538667
3                2601102  2011                     188.648718
4                2601102  2012                     186.921687
..                   ...   ...                            ...
259              2616001  2014                     190.654545
260              2616001  2015                     194.386667
261              2616001  2016                     191.966667
262              2616001  2017                     203.200000
263              2616001  2018                     200.233333

[264 rows x 3 columns]

## Grupo de Controle:
<hr style='border: 2px solid black;'>

In [295]:
selecao_municipios_controle = dados_municipios['codigo_do_municipio'].isin(codigos_municipios_controle)
selecao_municipios_controle

0       True
1       True
2       True
3       True
4       True
        ...
2029    True
2030    True
2031    True
2032    True
2033    True
Name: codigo_do_municipio, Length: 2024, dtype: bool

In [296]:
dados_municipios_controle = dados_municipios[selecao_municipios_controle]
dados_municipios_controle.reset_index(drop=True, inplace=True)

In [297]:
dados_municipios_controle

      codigo_do_municipio   ano  proficiencia_media_matematica
0                 2600054  2008                     166.225806
1                 2600054  2009                     167.251515
2                 2600054  2010                     169.137500
3                 2600054  2011                     177.648387
4                 2600054  2012                     176.574074
...                   ...   ...                            ...
1755              2616506  2014                     210.781818
1756              2616506  2015                     211.341667
1757              2616506  2016                     207.090909
1758              2616506  2017                     219.292308
1759              2616506  2018                     226.614286

[1760 rows x 3 columns]

# <font color='red' style='font-size: 30px;'>Exportando Arquivos:</font>
<hr style='border: 2px solid red;'>

In [ ]:
dados.to_csv('Dados/dados_escolas.csv', sep=',')

In [ ]:
dados_grupo_de_tratamento.to_csv('Dados/dados_escolas_tratamento.csv', sep=',')

In [ ]:
dados_grupo_de_controle.to_csv('Dados/dados_escolas_controle.csv', sep=',')

In [264]:
dados_municipios.to_csv('Dados/dados_municipios.csv', sep=',')

In [ ]:
dados_municipios_tratamento.to_csv('Dados/dados_municipios_tratamento.csv', sep=',')

In [ ]:
dados_municipios_controle.to_csv('Dados/dados_municipios_controle.csv', sep=',')

In [ ]:
codigos_municipios_tratados.to_csv('Dados/codigos_municipios_tratados.csv')

In [ ]:
codigos_municipios_controle.to_csv('Dados/codigos_municipios_controle.csv')