***
<h1 style='color: Darkblue; font-size: 36px; font-weight: bold;'>DESCRIÇÃO DO PROJETO</h1>

***
<h1 style='color: Darkblue; font-size: 25px; font-weight: bold;'>Condições Iniciais e Resultados Futuros:</h1>
    
<h1 style='color: Darkblue; font-size: 25px; font-weight: bold;'>Uma Avaliação de Impacto do Programa Mãe Coruja Pernambucana (PMCP) Sobre o Desempenho Escolar das Crianças</h1>

***
<h1 style='color: Darkblue; font-size: 18px; font-weight: bold;'>Neste projeto, tentaremos capturar o efeito causal do Programa Mãe Coruja Pernambucana sobre o desempenho escolar das crianças afetadas, com base nas proficiências médias das escolas divulgadas pelo Sistema de Avaliação Educacional de Pernambuco (SAEPE)</h1>

***

# <font color='darkblue'>PROGRAMA MÃE CORUJA PERNAMBUCANA (PMCP) </font>
<hr style='border: 2px solid darkblue;'>

### Implementado em 2008, no estado de Pernambuco, o Programa Mãe Coruja Pernambucana tinha como objetivo reduzir os altos índices de mortalidade infantil e materna no estado de Pernambuco.
    
### O PMCP atua por meio de uma extensa rede de ações calcadas em assistências no pré-natal, acompanhamento das crianças e auxílio durante a primeira infância, das quais o amparo ao período gestacional da mulher se destaca como o seu maior enfoque.

### Implementação:

***
#### A escolha da região e dos municípios por onde o programa começaria a ser implantado obedeceu a alguns critérios, sendo levada, ainda, em consideração as onze Gerências Regionais de Saúde (Geres) responsáveis pelos 185 municípios do estado. 

#### Os principais critérios utilizados foram a taxa de mortalidade infantil, os Índice de Desenvolvimento Humano (IDH) e Índice de Desenvolvimento Infantil (IDI). Seriam considerados aqueles municípios que possuíssem uma taxa de mortalidade infantil maior ou igual a 25 óbitos a cada mil nascidos vivos e que apresentassem baixos IDH e IDI. Além disso, determinou-se que o programa seria implantado em todos os municípios das Geres para os casos em que ao menos 50\% dos municípios nela situados  detivessem uma taxa de mortalidade infantil superior a 25 óbitos por mil nascidos vivos.


#### Com base nesses parâmetros, a implementação iniciou-se pela microregião de Araripina (Sertão do Araripe), seguida pelo Sertão do Moxotó (VI Geres). Desse modo, 24 municípios foram contemplados pelo PMCP em sua primeira fase de implementação. Ao longo dos anos o programa se ampliou de forma a atuar, atualmente, em 105 dos 185 municípios do estado.

#### A seguinte tabela fornece os anos de participação de cada município de Pernambuco no programa:

***

In [545]:
pd.read_excel('Dados/tabela_de_participacao.xls', index_col=0)

,Códigos dos Municípios,Participação dos Municípios no Programa Mãe Coruja Pernambucana ao longo do período de 2007 a 2014,2007,2008,2009,2010,2011,2012,2013,2014
0,2600054,Abreu e Lima,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
1,2600104,Afogados da Ingazeira,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
2,2600203,Afrânio,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM
3,2600302,Agrestina,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM
4,2600401,Água Preta,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
...,...,...,...,...,...,...,...,...,...,...
180,2616183,Vertente do Lério,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
181,2616209,Vertentes,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM
182,2616308,Vicência,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
183,2616407,Vitória de Santo Antão,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO,NÃO
184,2616506,Xexéu,NÃO,NÃO,SIM,SIM,SIM,SIM,SIM,SIM

### Ações Específicas do Programa:
***
<ul style='font-size: 14px; line-height: 2; text-align: justify;'>
    <li><b>círculos de educação e cultura</b></li>
    <li><b>cursos de qualificação profissional para as mães</b></li>
    <li><b>oficinas de segurança alimentar e nutricional</b></li>
    <li><b>inclusão em programas sociais nos Centros Regionais de Assistência Social</b></li>
    <li><b>fornecimento de kits do bebê para as gestantes</b></li>
    <li><b>assistência ao pré-natal (com a realização de sete ou mais consultas)</b></li>
    <li><b>assistência ao parto e ao puerpério</b></li>
    <li><b>reorganização da rede de atenção ao parto</b></li>
    <li><b>incentivo ao aleitamento materno</b></li>
    <li><b>acompanhamento e incentivo da vacinação da criança</b></li>
    <li><b>acesso ao registro de nascimento</b></li>
    <li><b>acompanhamento do crescimento e do desenvolvimento da criança</b></li>
</ul> 

***

### Fontes: 

https://maecoruja.pe.gov.br/o-programa/

http://portal.saude.pe.gov.br/programa/secretaria-executiva-de-atencao-saude/programa-mae-coruja-pernambucana

Livro Mãe Coruja Pernambucana (os 4 volumes), contidos em: https://maecoruja.pe.gov.br/leituras-importantes/

***



### Essas ações desempenhadas pelo PMCP refletem impactos exógenos em uma série de variáveis que podem afetar os resultados futuros das crianças, como a qualidade do pré-natal e da primeira infância, além da qualidade nutricional e o grau de instrução dos pais, sendo expressos, por exemplo, através dos resultados escolares.

***

### Referências:

ALMOND, D.; MAZUMDER, B.; EWIJK, R. V. In utero ramadan exposure and children’sacademic performance. The Economic Journal, Oxford University Press Oxford, UK, v. 125,n. 589, p. 1501–1533, 2014.

BROWNELL, M. D. et al. A population-based analysis of factors that predict early language andcognitive development.Early Childhood Research Quarterly, Elsevier, v. 35, p. 6–18, 2016.

CARNEIRO, P. M.; HECKMAN, J. J. Human capital policy. IZA discussion paper, 2003.

CHORNIY, A. V.; CURRIE, J.; SONCHAK, L. Does Prenatal WIC Participation Improve Child Outcomes?[S.l.], 2018.

HECKMAN, J. J. et al. The rate of return to the highscope perry preschool program.Journal ofpublic Economics, Elsevier, v. 94, n. 1-2, p. 114–128, 2010.

HENRICHS, J. et al. Parental family stress during pregnancy and cognitive functioning in earlychildhood: The generation r study.Early Childhood Research Quarterly, Elsevier, v. 26, n. 3, p.332–343, 2011.

JUNIOR, M. V. W.; RIBEIRO, F. G.; PAESE, L. H. Z. Early childhood home-based programmesand school violence: evidence from brazil.Development in Practice, Taylor & Francis, p. 1–11,2021.

NISHIMURA, F. N.; MESQUITA, A. Efeitos do programa “primeira infância melhor” sobre os casos de desnutrição infantil,.In: ANPEC - 46ºEncontro Nacional de Economia, Rio deJaneiro-RJ, 2018

***

# <font color='darkblue'>SISTEMA DE AVALIAÇÃO EDUCACIONAL DE PERNAMBUCO (SAEPE) </font>
<hr style='border: 2px solid darkblue;'>

### O Sistema de Avaliação Educacional de Pernambuco (SAEPE) foi criado, em 2000, com o objetivo de aferir o desempenho dos alunos da rede pública e fomentar mudanças na educação oferecida pelo estado.

### Desde 2008, o programa passou por reestruturações, com avaliações em Língua Portuguesa e Matemática ocorrendo anualmente. Os dados, referentes ao desempenho dos estudantes dos Ensinos Fundamental e Médio, são disponibilizados em uma Plataforma criada em parceria com o CAEd/UFJF.

### O seguinte código retorna a base de dados do SAEPE para as avaliações de matemática, com dados desde 2008, que utilizaremos no projeto

In [548]:
pd.read_csv('Dados/mat.csv', index_col=0).head()

C:\Users\Admin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Rede,Código da Etapa,Etapa,Código da GRE,GRE,Código do Município,Município,Código da Escola,Escola,Edição,Proficiência Média,Desvio Padrão,Padrão de Desempenho,Elementar I,Elementar II,Básico,Desejável,Estudantes Previstos,Estudantes Efetivos,Percentual de Participação
Código da Rede,,,,,,,,,,,,,,,,,,,,
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050048,ESCOLA BENTO AMERICO,2008,"172,9","33,9",Elementar II,"27,7","32,3","35,4","4,6",-,65,-
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050102,ESCOLA JOAO MONTEIRO DE MELO,2008,"175,7","30,6",Elementar II,"18,7","48,0","25,3","8,0",-,75,-
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050137,ESCOLA MINISTRO MARCOS DE BARROS FREIRE,2008,"163,1","34,9",Elementar II,"35,9","34,4","25,0","4,7",-,64,-
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050188,ESCOLA PADRE GIOVANNI TONIUTTI,2008,"174,6","38,3",Elementar II,"28,3","32,1","30,2","9,4",-,53,-
1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,101,AGRESTE CENTRO NORTE(CARUARU),2601706,BELO JARDIM,26050200,ESCOLA PROFESSORA MARIA GALVAO,2008,"182,6","49,6",Elementar II,"31,4","22,9","28,6","17,1",-,35,-

### Para medir o efeito causal do PMCP, utilizaremos a coluna de "Proficiências Médias", como o resultado escolar.

### As colunas referentes aos municípios e anos (edição) serão a base para definirmos os grupos de tratamento e controle, com base no ano de entrada dos municípios no programa

### As colunas referentes às etapas (série escolar) e aos anos (edição) serão a base para definirmos os períodos pré e pós tratamento. Por exemplo, se formos analisar os 5º anos (que comporta crianças de 10 a 11 anos), temos que o período pré-tratamento se dá entre 2008 à 2017, sendo o ano de 2018 o primeiro período que o efeito causal pode ser capturado, pois as crianças expostas ao PMCP (nascidas a partir de 2008) estariam no 5º ano em 2018.

***

### Fonte: 

https://institucional.caeddigital.net/projetos/saepe-pe.html

***

<h1 style='color: green; font-size: 36px; font-weight: bold;'>Modelo de Controle Sintético:</h1>

### Para medir o efeito causal do PMCP nas proficiências médias das escolas, devemos obter a diferença entre as proficiências no período pós-tratamento na unidade tratada e as proficiências do seu contrafactual, isto é, as proficiências médias da unidade tratada se ela não tivesse sido exposta ao tratamento.

### No Modelo de Controle Sintético, o contrafactual da unidade tratada é obtido através de uma soma ponderada de unidades não tratadas dentro de uma "donor pool", de modo que os pesos atribuídos a cada unidade nessa "donor pool" minimize a distância entre a variável de interesse e as variáveis explicativas no período pré-tratamento.

### Diferentemente do método de diferenças em diferenças convencional, em que há usualmente incertezas sobre quais as unidades não tratadas são as mais apropriadas para servirem como grupo de controle, o método do controle sintético se constitui como um método explícito e intencional de seleção de um grupo de controle, com o objetivo de obter um grupo de controle semelhante ao grupo tratado, em particular no que diz respeito à tendência temporal da variável de resultado antes do efeito exógeno estudado.

***
#### Fontes: 

https://www.urban.org/sites/default/files/publication/89246/the_synthetic_control_method_as_a_tool_0.pdf

https://www.itausocial.org.br/wp-content/uploads/2018/05/avaliacao-economica-3a-ed_1513188151.pdf

***

# <font color='red' style='font-size: 30px;'>Base de Dados Adequada ao Modelo:</font>
<hr style='border: 2px solid red;'>

### Neste Notebook Criaremos Uma Nova Base de Dados que se Adeque aos Parâmetros do Pacote Synth do R, responsável por implementar o modelo. A escolha de rodar o modelo pelo R se dá pelo fato de a implementação do modelo ser mais simples.

### Os dados a serem utilizados no modelo serão agregados por municípios e consideraremos a média de todas as escolas tratadas como uma única unidade tratada (um município tratado médio) antes de partirmos para uma análise indivual do efeito em cada município. 
### Essa escolha se deve pelo fato do modelo ser usualmente mais empregado para dados em níveis mais agregados.

# <font color='red' style='font-size: 30px;'>Importando Pacotes:</font>
<hr style='border: 2px solid red;'>

In [2]:
import pandas as pd
import numpy as np

# <font color='red' style='font-size: 30px;'>Importando Dados:</font>
<hr style='border: 2px solid red;'>

## Definição de Cada Banco Distinto de Dados:

**dados_escolas:** Dados desagregados por escolas

**dados_escolas_tratamento:** Dados desagregados por escolas dentro do grupo de tratamento

**dados_escolas_controle:** Dados desagregados por escolas dentro do grupo de controle

**dados_municipios:** Dados agregados por municípios

**dados_municipios_tratamento:** Dados agregados por municípios tratados

**dados_municipios_controle:** Dados agregados por municípios não tratados

In [38]:
dados_escolas_tratamento = pd.read_csv('Dados/dados_escolas_tratamento.csv', index_col=0)

In [178]:
dados_municipios = pd.read_csv('Dados/dados_municipios.csv', index_col=0)

In [179]:
dados_municipios

      codigo_do_municipio   ano  proficiencia_media_matematica
0                 2600054  2008                     166.225806
1                 2600054  2009                     167.251515
2                 2600054  2010                     169.137500
3                 2600054  2011                     177.648387
4                 2600054  2012                     176.574074
...                   ...   ...                            ...
2029              2616506  2014                     210.781818
2030              2616506  2015                     211.341667
2031              2616506  2016                     207.090909
2032              2616506  2017                     219.292308
2033              2616506  2018                     226.614286

[2024 rows x 3 columns]

# <font color='red' style='font-size: 30px;'>Preditores:</font>
<hr style='border: 2px solid red;'>

### No modelo de controle sintético, os preditores são análogos às variáveis de controle em modelos mais convencionais para a análise de políticas públicas. Isto é, ao selecionar preditores para o nosso modelo, devemos escolher variáveis que definam nosso outcom mas que não estejam correlacionadas entre si e com o efeito do tratamento.

### Os Preditores selecionados dizem respeito à:

#### Qualidade dos professores: 
<ul style='font-size: 14px; line-height: 2; text-align: justify;'>   
    <li><b>% de docentes com formação adequada no ensino fundamental</b></li>
</ul>

#### Qualidade da infraestrutura das escolas: 
<ul style='font-size: 14px; line-height: 2; text-align: justify;'>
    <li><b>% de alunos do ensino fundamental em escolas com laboratório de informática</b></li>
    <li><b>% de alunos do ensino fundamental em escolas com acesso à internet</b></li>
</ul>   

**Todos os dados estão agregados a níveis municipais e foram obtidos no site Atlas Brasil**

### Fonte:

http://www.atlasbrasil.org.br/

In [180]:
preditores = pd.read_csv('Dados/preditores_controle_sintetico.csv', index_col=0)
preditores

,Códigos dos Municípios,Nome dos Municípios,Anos,Porcentagem de Docentes com Formação Adequada no Fundamental,Porcentagem de Alunos do Ensino Fundamental em Escolas com Laboratório de Informática,Porcentagem de Alunos do Ensino Fundamental em Escolas com Acesso à Internet
1,2600054,Abreu E Lima (PE),2008,NaN,NaN,NaN
2,2600054,Abreu E Lima (PE),2009,NaN,NaN,NaN
3,2600054,Abreu E Lima (PE),2010,NaN,NaN,NaN
4,2600054,Abreu E Lima (PE),2011,NaN,NaN,NaN
5,2600054,Abreu E Lima (PE),2012,NaN,NaN,NaN
...,...,...,...,...,...,...
2009,2616506,Xexéu (PE),2014,21.3,32.01,81.68
2010,2616506,Xexéu (PE),2015,22.1,33.85,91.03
2011,2616506,Xexéu (PE),2016,22.1,29.61,91.02
2012,2616506,Xexéu (PE),2017,20.4,26.14,90.68
2013,2616506,Xexéu (PE),2018,NaN,NaN,NaN

**Nota-se que não há dados dos preditores para todos os períodos do SAEPE (2008-2018). Para todos os preditores, temos dados apenas a partir de 2013. Os dados de 2018 não são necessários, pois, para estimar o modelo precisamos de informações do período pré-tratamento para os preditores.**

## Comparando os Códigos dos Municípios

In [181]:
print('Número de linhas na base de dados do SAEPE (municipal): {}'.format(dados_municipios.shape[0]))
print('Número de linhas na base de dados dos Preditores (municipal): {}'.format(preditores.shape[0]))

Número de linhas na base de dados do SAEPE (municipal): 2024
Número de linhas na base de dados dos Preditores (municipal): 2013

**Percebe-se que os dados dos preditores possuem 11 observações a menos, o que indica que não temos dados dos preditores para algum município da nossa base de dados.**

**É necessário identificar esse município e excluí-lo da base de dados.**

In [23]:
codigos_municipios_PMCP = dados_municipios['codigo_do_municipio'].unique()
codigos_municipios_preditores = preditores['Códigos dos Municípios'].unique()

In [30]:
selecao_codigos_municipios = np.isin(codigos_municipios_PMCP, codigos_municipios_preditores, invert=True)
print('Código do Município faltante nos preditores: {}'.format(codigos_municipios_PMCP[selecao_codigos_municipios][0]))

Código do Município faltante nos preditores: 2612471

## Excluindo o Município Faltante da Base de Dados

In [33]:
dados_municipios = dados_municipios.query('codigo_do_municipio != 2612471').reset_index(drop=True)

In [34]:
dados_municipios

      codigo_do_municipio   ano  proficiencia_media_matematica
0                 2600054  2008                     166.225806
1                 2600054  2009                     167.251515
2                 2600054  2010                     169.137500
3                 2600054  2011                     177.648387
4                 2600054  2012                     176.574074
...                   ...   ...                            ...
2008              2616506  2014                     210.781818
2009              2616506  2015                     211.341667
2010              2616506  2016                     207.090909
2011              2616506  2017                     219.292308
2012              2616506  2018                     226.614286

[2013 rows x 3 columns]

# <font color='red' style='font-size: 30px;'>Construindo a Base de Dados do Modelo:</font>
<hr style='border: 2px solid red;'>

## Combinando as informações do SAEPE e dos Preditores em um único DataFrame

**É necessário adicionar os dados das proficiências médias contidos em "dados_municipios" com os dados dos preditores contidos em "preditores" (ambos agregados por municípios).**

In [95]:
dados_municipios.sort_values(['codigo_do_municipio', 'ano'], inplace=True)

In [99]:
dados_municipios.head()

   codigo_do_municipio   ano  proficiencia_media_matematica
0              2600054  2008                     166.225806
1              2600054  2009                     167.251515
2              2600054  2010                     169.137500
3              2600054  2011                     177.648387
4              2600054  2012                     176.574074

In [121]:
preditores.sort_values(['Códigos dos Municípios', 'Anos'], inplace=True)
preditores.reset_index(drop=True, inplace=True)

In [122]:
preditores.head()

,Códigos dos Municípios,Nome dos Municípios,Anos,Porcentagem de Docentes com Formação Adequada no Fundamental,Porcentagem de Alunos do Ensino Fundamental em Escolas com Laboratório de Informática,Porcentagem de Alunos do Ensino Fundamental em Escolas com Acesso à Internet
0,2600054,Abreu E Lima (PE),2008,NaN,NaN,NaN
1,2600054,Abreu E Lima (PE),2009,NaN,NaN,NaN
2,2600054,Abreu E Lima (PE),2010,NaN,NaN,NaN
3,2600054,Abreu E Lima (PE),2011,NaN,NaN,NaN
4,2600054,Abreu E Lima (PE),2012,NaN,NaN,NaN

In [123]:
dados_municipios_proficiencia_media = dados_municipios['proficiencia_media_matematica']
dados_municipios_proficiencia_media

0       166.225806
1       167.251515
2       169.137500
3       177.648387
4       176.574074
           ...
2008    210.781818
2009    211.341667
2010    207.090909
2011    219.292308
2012    226.614286
Name: proficiencia_media_matematica, Length: 2013, dtype: float64

**Também Iremos Adicionar a Variação Anual das Proficiências Médias Como Uma Medida Alternativa do Efeito do Programa.**

In [157]:
dados_municipios_variacao_proficiencia_media = dados_municipios.groupby(['codigo_do_municipio'])['proficiencia_media_matematica'].diff()
dados_municipios_variacao_proficiencia_media.rename(axis=None, inplace=True)

0             NaN
1        1.025709
2        1.885985
3        8.510887
4       -1.074313
          ...
2008    20.324675
2009     0.559848
2010    -4.250758
2011    12.201399
2012     7.321978
Length: 2013, dtype: float64

In [159]:
dados_controle_sintetico = pd.concat([preditores.iloc[:, 0:3], dados_municipios_proficiencia_media,
                                      dados_municipios_variacao_proficiencia_media, 
                                      preditores.iloc[:, 3:]], axis=1)
dados_controle_sintetico.rename(columns={ 
    'Códigos dos Municípios':'codigo_do_municipio',
    'Nome dos Municípios' : 'nome_do_municipio',
    'Anos' : 'ano',
    'Proficiência Média' : 'proficiencia_media_matematica',
    dados_controle_sintetico.columns[4] : 'variacao_proficiencia_media_matematica',
    'Porcentagem de Docentes com Formação Adequada no Fundamental' : 'porcentagem_de_docentes_com_formacao_adequada_no_fundamental',
    'Porcentagem de Alunos do Ensino Fundamental em Escolas com Laboratório de Informática' : 'porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_laboratorio_de_informatica',
    'Porcentagem de Alunos do Ensino Fundamental em Escolas com Acesso à Internet' : 'porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_acesso_a_internet'
    }, inplace=True)
dados_controle_sintetico

,codigo_do_municipio,nome_do_municipio,ano,proficiencia_media_matematica,variacao_proficiencia_media_matematica,porcentagem_de_docentes_com_formacao_adequada_no_fundamental,porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_laboratorio_de_informatica,porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_acesso_a_internet
0,2600054,Abreu E Lima (PE),2008,166.225806,NaN,NaN,NaN,NaN
1,2600054,Abreu E Lima (PE),2009,167.251515,1.025709,NaN,NaN,NaN
2,2600054,Abreu E Lima (PE),2010,169.137500,1.885985,NaN,NaN,NaN
3,2600054,Abreu E Lima (PE),2011,177.648387,8.510887,NaN,NaN,NaN
4,2600054,Abreu E Lima (PE),2012,176.574074,-1.074313,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2008,2616506,Xexéu (PE),2014,210.781818,20.324675,21.3,32.01,81.68
2009,2616506,Xexéu (PE),2015,211.341667,0.559848,22.1,33.85,91.03
2010,2616506,Xexéu (PE),2016,207.090909,-4.250758,22.1,29.61,91.02
2011,2616506,Xexéu (PE),2017,219.292308,12.201399,20.4,26.14,90.68
2012,2616506,Xexéu (PE),2018,226.614286,7.321978,NaN,NaN,NaN

## <font color='black'>Obtendo o Município Médio Tratado Agregado:</font>
<hr style='border: 2px solid black;'>

**Como dito anteriormente, ao invés de partimos direto para uma análise direta de cada município tratado individualmente, iremos tentar analisar o efeito médio total nos tratados.**

**Para isso, iremos tirar a média aritmética de todas as escolas tratadas (que foi trabalhada na etapa da análise descritiva e exploratória dos dados) e considerar esse resultado como um Município Médio Tratado.**

### Médias das Proficiências Médias:

In [169]:
proficiencias_medias_municipios_tratados = dados_escolas_tratamento.groupby('Edição')['Proficiência Média'].mean().reset_index(drop=True)
proficiencias_medias_municipios_tratados

0     159.349873
1     169.528241
2     169.020028
3     182.729421
4     187.686154
5     183.755929
6     183.917052
7     188.308224
8     185.754348
9     190.292323
10    200.600840
Name: Proficiência Média, dtype: float64

### Variação das Proficiências Médias:

In [165]:
dados_escolas_tratamento.head()

,Código da Rede,Rede,Código da Etapa,Etapa,Código da GRE,GRE,Código do Município,Município,Código da Escola,Escola,...,Proficiência Média,Desvio Padrão,Padrão de Desempenho,Elementar I,Elementar II,Básico,Desejável,Estudantes Previstos,Estudantes Efetivos,Percentual de Participação
0,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,111,SERTAO CENTRAL(SALGUEIRO),2610400,PARNAMIRIM,26010607,ESCOLA EUCLIDES DA CUNHA,...,162.0,"35,4",Elementar II,"41,2","33,3","23,5","2,0",-,51,-
1,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,111,SERTAO CENTRAL(SALGUEIRO),2614303,MOREILANDIA,26008467,ESCOLA CORONEL CHICO ROMAO,...,176.0,"44,5",Elementar II,"30,5","30,5","20,3","18,6",-,59,-
2,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,113,SERTAO DO ARARIPE(ARARIPINA),2602001,BODOCO,26001900,ESCOLA JOAO CARLOS LOCIO DE ALMEIDA,...,146.1,"39,0",Elementar I,"43,5","43,5","13,0","0,0",-,23,-
3,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,114,SERTAO DO MOXOTO IPANEMA(ARCOVERDE),2601201,ARCOVERDE,26024721,ESCOLA ANTONIO JAPIASSU,...,204.9,"43,4",Básico,"11,1","22,2","38,9","27,8",-,18,-
4,1,ESTADUAL,5,4ª SÉRIE/5º ANO EF,114,SERTAO DO MOXOTO IPANEMA(ARCOVERDE),2601201,ARCOVERDE,26024730,ESCOLA CARLOS RIOS,...,177.3,"39,4",Elementar II,"21,1","42,1","21,1","15,8",-,38,-

In [170]:
variacao_proficiencias_medias_municipios_tratados = dados_escolas_tratamento.groupby('Edição')['Proficiência Média'].mean().diff().reset_index(drop=True)
variacao_proficiencias_medias_municipios_tratados.rename(axis=None, inplace=True)

0           NaN
1     10.178369
2     -0.508213
3     13.709393
4      4.956733
5     -3.930225
6      0.161122
7      4.391173
8     -2.553876
9      4.537975
10    10.308518
dtype: float64

### Preditores:

In [49]:
codigos_municipios_tratados = pd.read_csv('Dados/codigos_municipios_tratados.csv', index_col=0)
codigos_municipios_tratados = codigos_municipios_tratados['Códigos dos Municípios']
codigos_municipios_tratados

0     2601102
1     2601201
2     2602001
3     2602803
4     2605103
5     2605301
6     2606309
7     2606606
8     2607000
9     2607307
10    2608057
11    2609154
12    2614303
13    2609907
14    2610400
15    2610806
16    2611002
17    2612455
18    2612554
19    2614105
20    2614808
21    2615607
22    2615805
23    2616001
Name: Códigos dos Municípios, dtype: int64

In [51]:
selecao_preditores_municipios_tratados = preditores['Códigos dos Municípios'].isin(codigos_municipios_tratados)
preditores_municipios_tratados = preditores[selecao_preditores_municipios_tratados]
preditores_municipios_tratados

,Códigos dos Municípios,Nome dos Municípios,Anos,Porcentagem de Docentes com Formação Adequada no Fundamental,Porcentagem de Alunos do Ensino Fundamental em Escolas com Laboratório de Informática,Porcentagem de Alunos do Ensino Fundamental em Escolas com Acesso à Internet
133,2601102,Araripina (PE),2008,NaN,NaN,NaN
134,2601102,Araripina (PE),2009,NaN,NaN,NaN
135,2601102,Araripina (PE),2010,NaN,NaN,NaN
136,2601102,Araripina (PE),2011,NaN,NaN,NaN
137,2601102,Araripina (PE),2012,NaN,NaN,NaN
...,...,...,...,...,...,...
1943,2616001,Venturosa (PE),2014,34.7,87.89,83.01
1944,2616001,Venturosa (PE),2015,32.8,80.65,87.82
1945,2616001,Venturosa (PE),2016,34.9,79.49,92.77
1946,2616001,Venturosa (PE),2017,36.5,78.72,92.91
1947,2616001,Venturosa (PE),2018,NaN,NaN,NaN

In [75]:
docentes_com_formacao_adequada = preditores_municipios_tratados.groupby('Anos')['Porcentagem de Docentes com Formação Adequada no Fundamental'].mean()
docentes_com_formacao_adequada.reset_index(drop=True, inplace=True)

In [73]:
escolas_com_laboratorio_informatica = preditores_municipios_tratados.groupby('Anos')['Porcentagem de Alunos do Ensino Fundamental em Escolas com Laboratório de Informática'].mean()
escolas_com_laboratorio_informatica.reset_index(drop=True, inplace=True)

In [74]:
escolas_com_acesso_a_internet = preditores_municipios_tratados.groupby('Anos')['Porcentagem de Alunos do Ensino Fundamental em Escolas com Acesso à Internet'].mean()
escolas_com_acesso_a_internet.reset_index(drop=True, inplace=True)

### Criando Demais Colunas:

**Para deixar esse município médio formatado de acordo com nossa nova base de dados, devemos adicionar colunas referentes ao seu código de identificação, ao seu nome e aos anos referentes a cada informação da proficiência média.**

In [91]:
codigo_municipio_tratado_medio = pd.Series(list(map(int,[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])), name='Códigos dos Municípios')
nome_do_municipio_tratado_medio = pd.Series(['Média dos Municípios Tradados', 'Média dos Municípios Tradados', 'Média dos Municípios Tradados',
                                  'Média dos Municípios Tradados', 'Média dos Municípios Tradados', 'Média dos Municípios Tradados',
                                  'Média dos Municípios Tradados', 'Média dos Municípios Tradados', 'Média dos Municípios Tradados',
                                  'Média dos Municípios Tradados', 'Média dos Municípios Tradados'], name='Nome dos Municípios')
anos = []
for ano in range(2008,2019):
    anos.append(ano)
    
anos = pd.Series(map(int,anos), name='Anos')

In [92]:
anos

0     2008
1     2009
2     2010
3     2011
4     2012
5     2013
6     2014
7     2015
8     2016
9     2017
10    2018
Name: Anos, dtype: int64

### Montando a Tabela do Município Tratado Médio

In [171]:
municipio_tratado_medio = pd.concat([codigo_municipio_tratado_medio, nome_do_municipio_tratado_medio, anos,
                                     proficiencias_medias_municipios_tratados, 
                                     variacao_proficiencias_medias_municipios_tratados,
                                     docentes_com_formacao_adequada, 
                                     escolas_com_laboratorio_informatica, escolas_com_acesso_a_internet], axis=1)
municipio_tratado_medio

,Códigos dos Municípios,Nome dos Municípios,Anos,Proficiência Média,0,Porcentagem de Docentes com Formação Adequada no Fundamental,Porcentagem de Alunos do Ensino Fundamental em Escolas com Laboratório de Informática,Porcentagem de Alunos do Ensino Fundamental em Escolas com Acesso à Internet
0,1,Média dos Municípios Tradados,2008,159.349873,NaN,NaN,NaN,NaN
1,1,Média dos Municípios Tradados,2009,169.528241,10.178369,NaN,NaN,NaN
2,1,Média dos Municípios Tradados,2010,169.020028,-0.508213,NaN,NaN,NaN
3,1,Média dos Municípios Tradados,2011,182.729421,13.709393,NaN,NaN,NaN
4,1,Média dos Municípios Tradados,2012,187.686154,4.956733,NaN,NaN,NaN
5,1,Média dos Municípios Tradados,2013,183.755929,-3.930225,27.183333,58.210833,66.346667
6,1,Média dos Municípios Tradados,2014,183.917052,0.161122,29.520833,56.990417,67.655833
7,1,Média dos Municípios Tradados,2015,188.308224,4.391173,31.104167,51.506250,73.690000
8,1,Média dos Municípios Tradados,2016,185.754348,-2.553876,32.337500,49.895417,78.109167
9,1,Média dos Municípios Tradados,2017,190.292323,4.537975,31.933333,45.704167,78.146250
10,1,Média dos Municípios Tradados,2018,200.600840,10.308518,NaN,NaN,NaN

In [172]:
municipio_tratado_medio.rename(columns={ 
    'Códigos dos Municípios':'codigo_do_municipio',
    'Nome dos Municípios' : 'nome_do_municipio',
    'Anos' : 'ano',
    'Proficiência Média' : 'proficiencia_media_matematica',
     municipio_tratado_medio.columns[4] : 'variacao_proficiencia_media_matematica',
    'Porcentagem de Docentes com Formação Adequada no Fundamental' : 'porcentagem_de_docentes_com_formacao_adequada_no_fundamental',
    'Porcentagem de Alunos do Ensino Fundamental em Escolas com Laboratório de Informática' : 'porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_laboratorio_de_informatica',
    'Porcentagem de Alunos do Ensino Fundamental em Escolas com Acesso à Internet' : 'porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_acesso_a_internet'
    }, inplace=True)
municipio_tratado_medio.head()

,codigo_do_municipio,nome_do_municipio,ano,proficiencia_media_matematica,variacao_proficiencia_media_matematica,porcentagem_de_docentes_com_formacao_adequada_no_fundamental,porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_laboratorio_de_informatica,porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_acesso_a_internet
0,1,Média dos Municípios Tradados,2008,159.349873,NaN,NaN,NaN,NaN
1,1,Média dos Municípios Tradados,2009,169.528241,10.178369,NaN,NaN,NaN
2,1,Média dos Municípios Tradados,2010,169.020028,-0.508213,NaN,NaN,NaN
3,1,Média dos Municípios Tradados,2011,182.729421,13.709393,NaN,NaN,NaN
4,1,Média dos Municípios Tradados,2012,187.686154,4.956733,NaN,NaN,NaN

## <font color='black'>Base de Dados Final:</font>
<hr style='border: 2px solid black;'>

**Por fim, adicionamos as linhas referentes ao Município Médio Tratado ao nosso DataFrame.**

In [173]:
dados_controle_sintetico = pd.concat([municipio_tratado_medio, dados_controle_sintetico]).reset_index(drop=True)
dados_controle_sintetico

,codigo_do_municipio,nome_do_municipio,ano,proficiencia_media_matematica,variacao_proficiencia_media_matematica,porcentagem_de_docentes_com_formacao_adequada_no_fundamental,porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_laboratorio_de_informatica,porcentagem_de_alunos_do_ensino_fundamental_em_escolas_com_acesso_a_internet
0,1,Média dos Municípios Tradados,2008,159.349873,NaN,NaN,NaN,NaN
1,1,Média dos Municípios Tradados,2009,169.528241,10.178369,NaN,NaN,NaN
2,1,Média dos Municípios Tradados,2010,169.020028,-0.508213,NaN,NaN,NaN
3,1,Média dos Municípios Tradados,2011,182.729421,13.709393,NaN,NaN,NaN
4,1,Média dos Municípios Tradados,2012,187.686154,4.956733,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2019,2616506,Xexéu (PE),2014,210.781818,20.324675,21.3,32.01,81.68
2020,2616506,Xexéu (PE),2015,211.341667,0.559848,22.1,33.85,91.03
2021,2616506,Xexéu (PE),2016,207.090909,-4.250758,22.1,29.61,91.02
2022,2616506,Xexéu (PE),2017,219.292308,12.201399,20.4,26.14,90.68
2023,2616506,Xexéu (PE),2018,226.614286,7.321978,NaN,NaN,NaN

# Exportando a Tabela

In [175]:
dados_controle_sintetico.to_csv('Dados/dados_controle_sintetico.csv', encoding="utf-8-sig")

# <font color='red' style='font-size: 30px;'>Resultados Preliminares do Modelo no R:</font>
<hr style='border: 2px solid red;'>

### O script utilizado no R para rodar o modelo está no arquivo "controle sintetico.R" e nos gera os seguintes gráficos:

# Os modelos ainda estão em processo de aperfeiçoamento, podendo serem testadas demais especificações e ainda não foram realizados os testes de significância com testes de placebo. 

# Entretanto, é possível tirar alguns insights dos resultados preliminares

## Utilizando as Proficiências Médias como variável dependente:
<hr style='border: 2px solid black;'>

## Path Ploth:

<img width='1000px' src='Modelo de Controle Sintético/proficiencias_medias_matematica.png'>

## Gaps Plot:

<img width='600px' src='Modelo de Controle Sintético/gaps_proficiencias_medias_matematica.png'>

### <font color='darkblue'> Ao avaliar o gráfico de evolução das médias, pode-se chegar à conclusão de que foi encontrado um bom sintético, na medida em que, na maioria dos períodos, a nossa unidade sintética tenha seguido trajetórias paralelas de variação em comparação à unidade tratada, sugerindo algum efeito, ainda que de magnitude baixa, no ano período pós-tratamento.</font>

### <font color='darkblue'> Todavia, ao avaliar o gráfico de gaps, percebe-se que o gap entre a unidade tratada e a sintética em 2018 não foi maior que o gap em 2013, além de aparentar estar nos mesmos níveis dos gaps entre 2009 e 2010. Isso sugere, premilinarmente, uma menor significância deste resultado.</font> 

### <font color='darkblue'> Entretanto, pode-se considerar que de 2014 a 2017, o gap manteve-se bem comportado e negativo, com a proficiência da unidade tratada assumindo um valor maior que a proficiência da unidade sintética justamente em 2018</font>

## Utilizando as Variações Anuais das Proficiências Médias como variável dependente:
<hr style='border: 2px solid black;'>

<img width='1000px' src='Modelo de Controle Sintético/variacao_proficiencias_medias_matematica.png'>

<img width='600px' src='Modelo de Controle Sintético/gaps_variacao_proficiencias_medias_matematica.png'>

### <font color='darkblue'> Ao avaliar o path plot da variação anual das médias, pode-se chegar à conclusão de que foi encontrado um bom sintético, na medida em que as variações entre as curvas tenham seguido trajetórias semelhantes na maioria dos períodos, aparentando um efeito causal do PMCP em 2018 com uma magnitude maior do que a anteriormente sugerida com a trajetória das proficiências médias.</font>

### <font color='darkblue'> Ao avaliar o gráfico de gaps, percebe-se que o gap entre a unidade tratada e a sintética em 2018 foi maior do que os gaps de todos os períodos anteriores, o que seria um indício preliminar de maior significância deste resultado</font>